name: Build App, Unit tests and UI tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-unit_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Use Node.js 20x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Npm Install 
      run: npm install
    - name: Run unit tests
      run: npm run test:unit
    - name: Show my SoftUni username
      run: echo "ValeriDimov84"

  ui_tests:
    needs: build-unit_tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Use Node.js 20x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Npm Install 
      run: npm install
    - name: Install Playwright
      run: npx playwright install
    - name: Start app on localhost and close the open terminal
      run: npm start &
    - name: Run ui tests
      run: npm run test:ui